import requests
import json

# Local import for accessing the MODEL_URL constant
from constants import MODEL_URL


def prompt_llm(prompt: str) -> str:
    """
    Sends a prompt to a language model API and returns the model's response.

    Args:
        prompt (str): The user's input prompt to send to the language model.

    Returns:
        str: The response generated by the language model.
    """
    # Make a POST request to the language model API with the prompt
    response = requests.post(
        url=MODEL_URL,  # The URL of the language model API
        headers={
            "Content-Type": "application/json",  # Specify the content type as JSON
            "Authorization": "Bearer no-key"  # Placeholder authorization token
        },
        data=json.dumps({
            "model": "LLaMA_CPP",  # Specify the model to use
            "messages": [
                {
                    "role": "user",  # The role of the message sender
                    "content": prompt  # The actual prompt content
                }
            ]
        }),
    )
    # Parse the JSON response from the API
    response = response.json()
    # Extract the content of the first choice's message from the response
    response = response["choices"][0]["message"]["content"]
    return response
